#!/usr/bin/env python3
"""Synthesises every Silly Kitty sound effect as 16-bit mono WAV.

Standard library only and fully deterministic (fixed seed), so the committed
files can always be regenerated byte-for-byte.
Usage (from repo root): python3 tools/sfx.py [out_dir]   default: sillykitty/audio/sfx
"""
import math
import random
import struct
import sys
import wave
from pathlib import Path

RATE = 22050
PEAK = 0.9


def lowpass(samples, cutoffs):
    """One-pole low-pass filter with a per-sample cutoff in Hz."""
    out, y = [], 0.0
    for x, fc in zip(samples, cutoffs):
        y += (1.0 - math.exp(-2.0 * math.pi * fc / RATE)) * (x - y)
        out.append(y)
    return out


def envelope(n, attack, release):
    """Linear attack, then linear release over the last `release` seconds."""
    a, r = max(1, int(attack * RATE)), max(1, int(release * RATE))
    return [min(1.0, i / a, (n - i) / r) for i in range(n)]


def lerp_curve(points, n):
    """Piecewise-linear curve through (time_fraction, value) points."""
    out = []
    for i in range(n):
        t = i / max(1, n - 1)
        for (t0, v0), (t1, v1) in zip(points, points[1:]):
            if t0 <= t <= t1:
                out.append(v0 + (v1 - v0) * (t - t0) / max(1e-9, t1 - t0))
                break
    return out


def meow():
    n = int(0.55 * RATE)
    pitch = lerp_curve([(0, 430), (0.35, 760), (1, 500)], n)
    cutoff = lerp_curve([(0, 500), (0.3, 2600), (1, 700)], n)
    phase, raw = 0.0, []
    for i in range(n):
        vibrato = 1.0 + 0.02 * math.sin(2 * math.pi * 6 * i / RATE)
        phase = (phase + pitch[i] * vibrato / RATE) % 1.0
        raw.append(2.0 * phase - 1.0)
    env = envelope(n, 0.04, 0.2)
    return [s * e for s, e in zip(lowpass(raw, cutoff), env)]


def splash(rng):
    n = int(0.6 * RATE)
    noise = [rng.uniform(-1.0, 1.0) for _ in range(n)]
    cutoff = [4500 * math.exp(-4.5 * i / n) + 300 for i in range(n)]
    out = [s * math.exp(-5.0 * i / n) for i, s in enumerate(lowpass(noise, cutoff))]
    for start in (0.12, 0.2, 0.3, 0.41):
        s0, length = int(start * RATE), int(0.06 * RATE)
        for j in range(length):
            f = 300 + 700 * j / length
            out[s0 + j] += 0.35 * math.sin(2 * math.pi * f * j / RATE) * (1 - j / length)
    return out


def clear():
    notes = [(523.25, 0.11), (659.25, 0.11), (783.99, 0.11), (1046.5, 0.38)]
    out = []
    for freq, dur in notes:
        n = int(dur * RATE)
        for i in range(n):
            square = 1.0 if (freq * i / RATE) % 1.0 < 0.25 else -1.0
            out.append(0.5 * square * math.exp(-3.0 * i / n))
    return out


def boing():
    n = int(0.35 * RATE)
    phase, out = 0.0, []
    for i in range(n):
        t = i / n
        freq = 220 + 300 * t + 40 * math.sin(2 * math.pi * 14 * i / RATE) * (1 - t)
        phase += freq / RATE
        out.append(math.sin(2 * math.pi * phase) * (1 - t) ** 1.5)
    return out


def tick():
    n = int(0.05 * RATE)
    return [math.sin(2 * math.pi * 1800 * i / RATE) * math.exp(-60.0 * i / RATE) for i in range(n)]


def timeup():
    """Sad descending "wah-wah": two falling square-wave notes."""
    out = []
    for start, end, dur in ((392.0, 370.0, 0.28), (330.0, 247.0, 0.6)):
        n = int(dur * RATE)
        phase = 0.0
        cutoff = [1800 - 1200 * i / n for i in range(n)]
        raw = []
        for i in range(n):
            phase = (phase + (start + (end - start) * i / n) / RATE) % 1.0
            raw.append(1.0 if phase < 0.5 else -1.0)
        env = envelope(n, 0.02, 0.15)
        out += [s * e for s, e in zip(lowpass(raw, cutoff), env)]
    return out


def hum():
    """Vacuum motor drone. Every component is a whole number of cycles per
    second, so the 1-second clip loops seamlessly."""
    n = RATE
    out = []
    for i in range(n):
        t = i / RATE
        wobble = 1.0 + 0.25 * math.sin(2 * math.pi * 4 * t)
        tone = (math.sin(2 * math.pi * 110 * t) + 0.6 * math.sin(2 * math.pi * 220 * t)
                + 0.35 * math.sin(2 * math.pi * 330 * t) + 0.2 * math.sin(2 * math.pi * 1210 * t))
        buzz = 0.25 if (165 * t) % 1.0 < 0.5 else -0.25
        out.append((tone + buzz) * wobble)
    return out


def bark(rng):
    """Two quick "woof"s: a falling growly tone with a noisy attack."""
    out = []
    for dur, start, end in ((0.16, 520.0, 300.0), (0.22, 480.0, 250.0)):
        n = int(dur * RATE)
        phase, raw = 0.0, []
        for i in range(n):
            phase = (phase + (start + (end - start) * i / n) / RATE) % 1.0
            raw.append(2.0 * phase - 1.0 + rng.uniform(-0.6, 0.6) * math.exp(-12.0 * i / n))
        cutoff = [2200 - 1500 * i / n for i in range(n)]
        env = envelope(n, 0.01, dur * 0.6)
        out += [s * e for s, e in zip(lowpass(raw, cutoff), env)]
        out += [0.0] * int(0.07 * RATE)
    return out


def yawn():
    """Long sleepy "mraaawh": a slow rising-then-sagging vowel glide."""
    n = int(1.1 * RATE)
    pitch = lerp_curve([(0, 320), (0.35, 470), (1, 210)], n)
    cutoff = lerp_curve([(0, 400), (0.4, 1600), (1, 350)], n)
    phase, raw = 0.0, []
    for i in range(n):
        phase = (phase + pitch[i] / RATE) % 1.0
        raw.append(2.0 * phase - 1.0)
    env = envelope(n, 0.15, 0.45)
    return [s * e for s, e in zip(lowpass(raw, cutoff), env)]


def hiss(rng):
    """Angry cat hiss: bright noise with a sharp attack and a slow fade."""
    n = int(0.5 * RATE)
    noise = [rng.uniform(-1.0, 1.0) for _ in range(n)]
    smooth = lowpass(noise, [5000] * n)
    bright = [x - s for x, s in zip(noise, lowpass(noise, [1500] * n))]
    env = envelope(n, 0.02, 0.3)
    return [(b + 0.3 * s) * e for b, s, e in zip(bright, smooth, env)]


def write(path, samples):
    peak = max(abs(s) for s in samples) or 1.0
    frames = b"".join(struct.pack("<h", int(s / peak * PEAK * 32767)) for s in samples)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(frames)


def main():
    out_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "sillykitty/audio/sfx")
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(1002)
    sounds = {"meow": meow(), "splash": splash(rng), "clear": clear(), "boing": boing(),
              "tick": tick(), "timeup": timeup(), "hum": hum(), "bark": bark(rng), "yawn": yawn(),
              "hiss": hiss(rng)}
    for name, samples in sounds.items():
        path = out_dir / f"{name}.wav"
        write(path, samples)
        print(f"wrote {path} ({len(samples) / RATE:.2f}s)")


if __name__ == "__main__":
    main()
