#!/usr/bin/env python3
"""Synthesises every Silly Kitty sound effect as 16-bit mono WAV.

Standard library only and fully deterministic (fixed seed), so the committed
files can always be regenerated byte-for-byte.
Usage (from repo root): python3 tools/sfx.py [out_dir]   default: sillykitty/audio/sfx
"""
import math
import random
import struct
import sys
import wave
from pathlib import Path

RATE = 22050
PEAK = 0.9


def lowpass(samples, cutoffs):
    """One-pole low-pass filter with a per-sample cutoff in Hz."""
    out, y = [], 0.0
    for x, fc in zip(samples, cutoffs):
        y += (1.0 - math.exp(-2.0 * math.pi * fc / RATE)) * (x - y)
        out.append(y)
    return out


def envelope(n, attack, release):
    """Linear attack, then linear release over the last `release` seconds."""
    a, r = max(1, int(attack * RATE)), max(1, int(release * RATE))
    return [min(1.0, i / a, (n - i) / r) for i in range(n)]


def lerp_curve(points, n):
    """Piecewise-linear curve through (time_fraction, value) points."""
    out = []
    for i in range(n):
        t = i / max(1, n - 1)
        for (t0, v0), (t1, v1) in zip(points, points[1:]):
            if t0 <= t <= t1:
                out.append(v0 + (v1 - v0) * (t - t0) / max(1e-9, t1 - t0))
                break
    return out


def meow():
    n = int(0.55 * RATE)
    pitch = lerp_curve([(0, 430), (0.35, 760), (1, 500)], n)
    cutoff = lerp_curve([(0, 500), (0.3, 2600), (1, 700)], n)
    phase, raw = 0.0, []
    for i in range(n):
        vibrato = 1.0 + 0.02 * math.sin(2 * math.pi * 6 * i / RATE)
        phase = (phase + pitch[i] * vibrato / RATE) % 1.0
        raw.append(2.0 * phase - 1.0)
    env = envelope(n, 0.04, 0.2)
    return [s * e for s, e in zip(lowpass(raw, cutoff), env)]


def splash(rng):
    n = int(0.6 * RATE)
    noise = [rng.uniform(-1.0, 1.0) for _ in range(n)]
    cutoff = [4500 * math.exp(-4.5 * i / n) + 300 for i in range(n)]
    out = [s * math.exp(-5.0 * i / n) for i, s in enumerate(lowpass(noise, cutoff))]
    for start in (0.12, 0.2, 0.3, 0.41):
        s0, length = int(start * RATE), int(0.06 * RATE)
        for j in range(length):
            f = 300 + 700 * j / length
            out[s0 + j] += 0.35 * math.sin(2 * math.pi * f * j / RATE) * (1 - j / length)
    return out


def clear():
    notes = [(523.25, 0.11), (659.25, 0.11), (783.99, 0.11), (1046.5, 0.38)]
    out = []
    for freq, dur in notes:
        n = int(dur * RATE)
        for i in range(n):
            square = 1.0 if (freq * i / RATE) % 1.0 < 0.25 else -1.0
            out.append(0.5 * square * math.exp(-3.0 * i / n))
    return out


def boing():
    n = int(0.35 * RATE)
    phase, out = 0.0, []
    for i in range(n):
        t = i / n
        freq = 220 + 300 * t + 40 * math.sin(2 * math.pi * 14 * i / RATE) * (1 - t)
        phase += freq / RATE
        out.append(math.sin(2 * math.pi * phase) * (1 - t) ** 1.5)
    return out


def write(path, samples):
    peak = max(abs(s) for s in samples) or 1.0
    frames = b"".join(struct.pack("<h", int(s / peak * PEAK * 32767)) for s in samples)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(frames)


def main():
    out_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "sillykitty/audio/sfx")
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(1002)
    sounds = {"meow": meow(), "splash": splash(rng), "clear": clear(), "boing": boing()}
    for name, samples in sounds.items():
        path = out_dir / f"{name}.wav"
        write(path, samples)
        print(f"wrote {path} ({len(samples) / RATE:.2f}s)")


if __name__ == "__main__":
    main()
